services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672" # RabbitMQ default port
      - "15672:15672" # Management web UI port
    environment:
      RABBITMQ_HOST: '%'
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: root
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_network
    healthcheck:
      test:
          - CMD
          - rabbitmq-diagnostics
          - '-q'
          - ping
      retries: 3
      timeout: 5s

volumes:
  rabbitmq_data:

networks:
  rabbitmq_network:
    driver: bridge